[package]
name = "moduforge-collaboration-client"
version = {workspace=true}
edition = {workspace=true}
description = "moduforge 协作系统"
authors = {workspace=true}
license = {workspace=true}
documentation = {workspace=true}
homepage = {workspace=true}
repository = {workspace=true}

[lib]
name = "mf_collab_client"
path = "src/lib.rs"

[dependencies]
tokio =  { workspace=true }
tracing-subscriber = "0.3"
futures-util = "0.3"
serde = { workspace=true }
serde_json = { workspace=true }
uuid = { workspace=true }
anyhow = { workspace=true }
thiserror = { workspace=true }
tracing = "0.1"
dashmap = { workspace=true }

warp = "0.3.7"
yrs-warp = "0.8.0"
yrs = "0.18.2"
moduforge-model = {version = "0.4.6", path = "../model"}
moduforge-state = {version = "0.4.6", path = "../state"}
moduforge-transform = {version = "0.4.6", path = "../transform"}
moduforge-core = {version = "0.4.6", path = "../core"}
moduforge-macros = {version = "0.4.6", path = "../macro"}
async-trait =  { workspace=true }
fastrand = "2.0"
