[package]
name = "moduforge-collaboration-client"
version = {workspace=true}
edition = {workspace=true}
description = "moduforge 协作系统"
authors = {workspace=true}
license = {workspace=true}
documentation = {workspace=true}
homepage = {workspace=true}
repository = {workspace=true}

[lib]
name = "mf_collab_client"
path = "src/lib.rs"

[dependencies]
tokio =  { workspace=true }
tracing-subscriber = "0.3"
futures-util = "0.3"
serde_json = { workspace=true }
tracing = "0.1"

yrs-warp = "0.8.0"
yrs = "0.18.2"
tokio-tungstenite = "0.21"
url = "2.5"