edition="2024"
# 最大行宽
max_width = 80
# 硬性限制行宽
hard_tabs = false
# 缩进宽度
tab_spaces = 4
fn_params_layout="Vertical"
# 统一管理宽度设置，但不包含 comment_width
use_small_heuristics="MAX"
# 在match分支中，如果包含了块，也需要加逗号以示分隔
match_block_trailing_comma=true
# 当使用 extern 指定外部函数时，不需要显式指定 C-ABI ，默认就是 C-ABI
force_explicit_abi=false 
# 将多个 Derive 宏合并为同一行
merge_derives = true
reorder_imports = false

