[package]
name = "moduforge-collaboration"
version = {workspace=true}
edition = {workspace=true}
description = "moduforge 协作系统"
authors = {workspace=true}
license = {workspace=true}
documentation = {workspace=true}
homepage = {workspace=true}
repository = {workspace=true}

[dependencies]
tokio =  { workspace=true }
tracing-subscriber = "0.3"
futures-util = "0.3"
serde = { workspace=true }
serde_json = { workspace=true }
uuid = { workspace=true }
anyhow = { workspace=true }
thiserror = { workspace=true }
tracing = "0.1"
parking_lot ={ workspace=true }
dashmap = { workspace=true }
chrono = { version = "0.4", features = ["serde"] }
im = { workspace=true }
warp = "0.3.7"
yrs-warp = "0.8.0"
yrs = "0.18.2"
moduforge-model = {version = "0.4.5", path = "../model"}
moduforge-state = {version = "0.4.5", path = "../state"}
moduforge-transform = {version = "0.4.5", path = "../transform"}
moduforge-core = {version = "0.4.5", path = "../core"}
moduforge-macros = {version = "0.4.5", path = "../macro"}
async-trait =  { workspace=true }
lazy_static =  { workspace=true }
once_cell =  { workspace=true }
fastrand = "2.0"
