[package]
name = "moduforge-core"
version = {workspace=true}
edition = {workspace=true}
description = "moduforge 核心模块"
authors = {workspace=true}
license = {workspace=true}
documentation = {workspace=true}
homepage = {workspace=true}
repository = {workspace=true}
[lib]
name = "mf_core"
path = "src/lib.rs"



[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = {workspace=true}
lazy_static= {workspace=true}
async-channel= {workspace=true}
anyhow= {workspace=true}
im= {workspace=true}
chrono= {workspace=true}
serde = {workspace=true}
serde_json = {workspace=true}
thiserror= {workspace=true}
async-trait= {workspace=true}
futures = {workspace=true}
moduforge-model = {version = "0.4.5", path = "../model"}
moduforge-state = {version = "0.4.5", path = "../state"}
moduforge-transform = {version = "0.4.5", path = "../transform"}
metrics = "0.22.0"

[dev-dependencies]
rstest = "0.18.2"
